name: aramark-mlops-dev

# Controls when the action will run. 
on:
  push:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          DEV_ACCOUNT: ${{ secrets.DEV_ACCOUNT }}
          DEV_USER: ${{ secrets.DEV_USER }}
          DEV_ROLE: ${{ secrets.DEV_ROLE }}
          DEV_WAREHOUSE: ${{ secrets.DEV_WAREHOUSE }}
          DEV_DATABASE: ${{ secrets.DEV_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.DEV_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE -a $DEV_ACCOUNT -u $DEV_USERNAME -r $DEV_ROLE -w $DEV_WAREHOUSE -d $DEV_DATABASE -c $DEV_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
